<title>Room Type</title>
<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	//echo $this->headTitle($tr->translate('ADD_HOLIDAY'));
?>	
<?php  $holiday= $this->frm_holiday;?>
<script>
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.DateTextBox");
require(["dijit/form/CheckBox","dijit/Dialog","dijit/layout/TabContainer"]);
</script>
<form  id='add_techer' action="<?php echo $this->url(array('module'=>'room','controller'=>'index','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post"
 enctype="application/x-www-form-urlencoded">
 <script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			} else {
				return false;
			}
</script>
<table cellspacing="10" width="45%" style="margin: 0 auto;">
	<tr>
		<td>
		<fieldset>
					<legend align="center" ><strong><?php echo $tr->translate("ROOM_TYPE");?></strong></legend>
					<table style="margin: 0 auto; width: 95%;" cellspacing="10">
						<tr>
							<td><?php echo $tr->translate("ROOM_TYPE")?><input type="hidden" name="id" id="id" value="<?php echo $this->row_room_type['id'];?>"/></td>
							<td><input dojoType="dijit.form.ValidationTextBox" class="fullside" required="true" id="room_type" name="room_type" value="<?php echo $this->row_room_type['type'];?>" type="text"></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("STATUS")?></td>
							<td><select name="status" id="status" dojoType="dijit.form.FilteringSelect" required="true"  class="fullside">
											    <option value="1" label="Active">Active</option>
											    <option value="0" label="Deactive">Deactive</option>
											</select>
						   </td>
						</tr>
						<tr>
							<td colspan="4" align="center">
									<input type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVECLOSE');?>" dojoType="dijit.form.Button" 
										iconClass="dijitEditorIcon dijitEditorIconSave" />
									
							</td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>
