<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	//echo $this->headTitle($tr->translate('ADD_HOLIDAY'));
?>	
<title><?php echo $tr->translate("FLOOR");?></title>
<?php  $holiday= $this->frm_holiday;?>
<script>
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.DateTextBox");
require(["dijit/form/CheckBox","dijit/Dialog","dijit/layout/TabContainer"]);
</script>
<form  id='add_techer' action="<?php echo $this->url(array('module'=>'room','controller'=>'room','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post"
 enctype="application/x-www-form-urlencoded">
 <script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			} else {
				return false;
			}
</script>
<table cellspacing="10" width="90%" style="margin: 0 auto;">
	<tr>
		<td>
		<fieldset>
					<legend align="left" ><strong><?php echo $tr->translate("ADD_ROOM");?></strong></legend>
					<table cellspacing="15"  style="margin: 0 auto; width: 95%;" >
						<tr>
							<td><?php echo $tr->translate("ROOM_NO")?></td>
							<td><input dojoType="dijit.form.ValidationTextBox" class="fullside" required="true" id="room_no" name="room_no" value="" type="text"></td>
							<td><?php echo $tr->translate("ROOM_NUMBER")?></td>
							<td><input dojoType="dijit.form.NumberTextBox" class="fullside" required="true" id="room_number" name="room_number" value="" type="text"></td>
						</tr>
						<tr>
						    <td><?php echo $tr->translate("ROOM_TYPE")?></td>
                            <td><select name="room_type" id="room_type" dojoType="dijit.form.FilteringSelect"  class="fullside">
											    <?php foreach ($this->all_type As $rows){?>
											    <option value="<?php echo $rows['id'];?>" ><?php echo $rows['type'];?></option>
											    <?php }?>
								</select>
                            </td>
						    <td><?php echo $tr->translate("FLOOR_NAME")?></td>
						    <td><select name="floor_name" id="floor_name" dojoType="dijit.form.FilteringSelect"  class="fullside">
											    <?php foreach ($this->all_floor As $rows){?>
											    <option value="<?php echo $rows['id'];?>" ><?php echo $rows['floor_name'];?></option>
											    <?php }?>
											    
								</select>
                            </td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("DATE")?></td>
							<td><input dojoType="dijit.form.DateTextBox" class="fullside" required="true" id="date" name="date" value="now" type="text"></td>
							<td><?php echo $tr->translate("BED_NUMBER")?></td>
							<td><input dojoType="dijit.form.NumberTextBox" class="fullside" required="true" id="bet_number" name="bet_number" value="" type="text"></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("DESCRIPTION")?></td>
							<td><input dojoType="dijit.form.TextBox" class="fullside" required="true" id="description" name="description" value="" type="text"></td>
							<td><?php echo $tr->translate("STATUS")?></td>
							<td><select name="status" id="status" dojoType="dijit.form.FilteringSelect" required="true"  class="fullside">
											    <option value="1" label="Active">Active</option>
											    <option value="0" label="Deactive">Deactive</option>
											</select>
						   </td>
						</tr>
						<tr>
							<td colspan="4" align="center">
									<input type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>"dojoType="dijit.form.Button" iconClass="dijitIconClear"/>
									<input type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVECLOSE');?>" dojoType="dijit.form.Button" 
										iconClass="dijitEditorIcon dijitEditorIconSave" />
									<input type="submit" value="save_new" name="save_new" label="<?php echo $tr->translate('SAVENEW');?>" dojoType="dijit.form.Button" 
										iconClass="dijitEditorIcon dijitEditorIconSave" />
							</td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>
